"""create todo list

Revision ID: 9727b242a0bb
Revises: cc2ba5882711
Create Date: 2022-11-10 15:33:43.695036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9727b242a0bb'
down_revision = 'cc2ba5882711'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.Column('time_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todolists_id'), 'todolists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todolists_id'), table_name='todolists')
    op.drop_table('todolists')
    # ### end Alembic commands ###
